apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secrets
  namespace: streamingapp

type: Opaque

stringData:
  JWT_SECRET: "REPLACE_ME"
  MONGO_URI: "mongodb://mongo-service:27017/streamingapp"
  AWS_ACCESS_KEY_ID: "REPLACE_ME"
  AWS_SECRET_ACCESS_KEY: "REPLACE_ME"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "streamingapp-videos"
  AWS_CDN_URL: "https://REPLACE.cloudfront.net"
  CLIENT_URLS: "https://streamingapp.example.com"
  STREAMING_PUBLIC_URL: "https://streamingapp.example.com"
